import type { Post } from '@/types/post'

export interface SociamonialsCSVRow {
  Message: string
  Link: string
  ImageURL: string
  Month: string
  Day: string
  Year: string
  Hour: string
  Minute: string
  PinTitle: string
  Category: string
  Watermark: string
  HashtagGroup: string
  VideoThumbnailURL: string
  CTAGroup: string
  FirstComment: string
  Story: string
  PinterestBoard: string
  AltText: string
  PostPreset: string
  TeamNote: string
}

export interface CSVGenerationOptions {
  clientName: string
  categoryName?: string
  scheduleType: 'queue' | 'specific_times' | 'random'
  postsPerWeek?: number
  preferredPostingHours?: number[]
  includeFirstComment?: boolean
  includeAltText?: boolean
}

export function generateCSV(
  posts: Post[],
  options: CSVGenerationOptions
): string {
  // CSV header
  const headers = [
    'Message',
    'Link',
    'ImageURL',
    'Month',
    'Day',
    'Year',
    'Hour',
    'Minute',
    'PinTitle',
    'Category',
    'Watermark',
    'HashtagGroup',
    'VideoThumbnailURL',
    'CTAGroup',
    'FirstComment',
    'Story',
    'PinterestBoard',
    'AltText',
    'PostPreset',
    'TeamNote',
  ]

  const rows: SociamonialsCSVRow[] = []

  // Generate schedule based on options
  const schedule = generateSchedule(posts.length, options)

  posts.forEach((post, index) => {
    const scheduleSlot = schedule[index] || {
      month: new Date().getMonth() + 1,
      day: new Date().getDate(),
      year: new Date().getFullYear(),
      hour: 11,
      minute: 'Random',
    }

    // Extract hashtags from caption
    const hashtagMatch = post.caption_text.match(/(#[\w]+)+/g)
    const hashtagsInCaption = hashtagMatch ? hashtagMatch.join(' ') : ''
    
    // Remove hashtags from main caption for cleaner look
    const cleanCaption = post.caption_text.replace(/(#[\w]+\s*)+/g, '').trim()

    // Build first comment (hashtags + optional additions)
    const firstComment = options.includeFirstComment
      ? hashtagsInCaption
      : ''

    // Build alt text
    const altText = options.includeAltText
      ? `Social media post: ${post.image_filename || 'Image'}`
      : ''

    const row: SociamonialsCSVRow = {
      Message: escapeCSVField(cleanCaption),
      Link: '', // No external link for standalone posts
      ImageURL: post.image_url,
      Month: scheduleSlot.month.toString(),
      Day: scheduleSlot.day.toString(),
      Year: scheduleSlot.year.toString(),
      Hour: scheduleSlot.hour.toString(),
      Minute: scheduleSlot.minute.toString(),
      PinTitle: '', // Optional for Pinterest
      Category: options.categoryName || options.clientName || '',
      Watermark: '', // Optional
      HashtagGroup: '', // Optional - we're using direct hashtags
      VideoThumbnailURL: '', // Not a video
      CTAGroup: '', // Optional
      FirstComment: escapeCSVField(firstComment),
      Story: 'N', // Not a story
      PinterestBoard: '', // Optional
      AltText: escapeCSVField(altText),
      PostPreset: '', // Use default settings
      TeamNote: options.clientName ? `Generated by SocialDrive AI for ${options.clientName}` : '',
    }

    rows.push(row)
  })

  // Convert to CSV string
  const csvRows = [
    headers.join(','),
    ...rows.map(row => 
      headers.map(header => row[header as keyof SociamonialsCSVRow]).join(',')
    ),
  ]

  return csvRows.join('\n')
}

function generateSchedule(
  postCount: number,
  options: CSVGenerationOptions
): Array<{
  month: number
  day: number
  year: number
  hour: number
  minute: string | number
}> {
  const schedule: Array<{
    month: number
    day: number
    year: number
    hour: number
    minute: string | number
  }> = []

  const now = new Date()
  let currentDate = new Date(now)

  // Default posting hours if not specified
  const preferredHours = options.preferredPostingHours || [11, 14, 18, 20] // 11am, 2pm, 6pm, 8pm

  for (let i = 0; i < postCount; i++) {
    // For queue-based posting, use current date
    if (options.scheduleType === 'queue') {
      schedule.push({
        month: currentDate.getMonth() + 1,
        day: currentDate.getDate(),
        year: currentDate.getFullYear(),
        hour: 0, // Will be queued, not scheduled
        minute: 'Random',
      })
    } else {
      // Specific time scheduling
      const hour = preferredHours[i % preferredHours.length]
      
      schedule.push({
        month: currentDate.getMonth() + 1,
        day: currentDate.getDate(),
        year: currentDate.getFullYear(),
        hour,
        minute: 'Random', // Let Sociamonials randomize the minute
      })

      // Move to next day after certain number of posts
      if ((i + 1) % (options.postsPerWeek || 5) === 0) {
        currentDate.setDate(currentDate.getDate() + 1)
      }
    }
  }

  return schedule
}

function escapeCSVField(value: string): string {
  if (!value) return ''
  
  // If field contains comma, newline, or quote, wrap in quotes and escape quotes
  if (value.includes(',') || value.includes('\n') || value.includes('"')) {
    return `"${value.replace(/"/g, '""')}"`
  }
  
  return value
}

export function downloadCSV(csvContent: string, filename: string): void {
  // Client-side download (for browser)
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const link = document.createElement('a')
  const url = URL.createObjectURL(blob)
  
  link.setAttribute('href', url)
  link.setAttribute('download', filename)
  link.style.visibility = 'hidden'
  
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

export function validateCSV(posts: Post[]): {
  valid: boolean
  errors: string[]
  warnings: string[]
} {
  const errors: string[] = []
  const warnings: string[] = []

  posts.forEach((post, index) => {
    // Validate image URL
    if (!post.image_url) {
      errors.push(`Post ${index + 1}: Missing image URL`)
    } else if (!post.image_url.startsWith('http')) {
      errors.push(`Post ${index + 1}: Image URL must be publicly accessible (http/https)`)
    }

    // Validate caption
    if (!post.caption_text) {
      errors.push(`Post ${index + 1}: Missing caption`)
    } else if (post.caption_text.length > 2200) {
      warnings.push(`Post ${index + 1}: Caption is very long (${post.caption_text.length} chars). Instagram limit is 2,200.`)
    }

    // Validate caption length per platform
    if (post.caption_text.length > 280) {
      warnings.push(`Post ${index + 1}: Caption exceeds Twitter/X limit (280 chars)`)
    }

    // Check for broken image URLs
    if (post.image_url.includes('drive.google.com')) {
      warnings.push(`Post ${index + 1}: Google Drive URLs may not work. Use direct image URLs instead.`)
    }
  })

  return {
    valid: errors.length === 0,
    errors,
    warnings,
  }
}

export function getCSVPreview(posts: Post[], options: CSVGenerationOptions): {
  totalPosts: number
  scheduledDateRange: string
  estimatedTime: string
  platformCompatibility: {
    instagram: boolean
    facebook: boolean
    linkedin: boolean
    twitter: boolean
  }
} {
  const schedule = generateSchedule(posts.length, options)
  
  const startDate = new Date()
  const endDate = new Date()
  endDate.setDate(endDate.getDate() + Math.ceil(posts.length / (options.postsPerWeek || 5)))

  return {
    totalPosts: posts.length,
    scheduledDateRange: `${startDate.toLocaleDateString()} - ${endDate.toLocaleDateString()}`,
    estimatedTime: `${posts.length} posts scheduled`,
    platformCompatibility: {
      instagram: true,
      facebook: true,
      linkedin: true,
      twitter: posts.every(p => p.caption_text.length <= 280),
    },
  }
}
